### ISSUE TITLE
EVENT_BEFORE_VALIDATE of a behavior attached to the PostLang Model will not trigger.

### ISSUE THREAD

**Issue by tracid** [OmgDef/yii2-multilingual-behavior#14]
Hi,

is it by design, a bug, or am i doing something wrong? I have a Problem adding the SluggableBehavior to my PostLang Model. The new Slug wont be saved in this case. But with a Behavior made with EVENT_BEFORE_UPDATE, everything works fine.

The Post Model is validated before saving...

Thanks!

**Comment by OmgDef** [comment]
@tracid Hi! Thanks for reporting. I fixed this issue in master. Don't forget add slug attribute to the list of multilingual attributes

**Comment by tracid** [comment]
@OmgDef Hi, it works fine now! Thanks for the fast fix, i really appreciate the Script! :)
