### ISSUE TITLE
Custom Scopes

### ISSUE THREAD

**Issue by andreCatita** [OmgDef/yii2-multilingual-behavior#20]
Hello again @OmgDef,

How do you handle Custom Scoping, with your MultlingualBehavior?
Do we at all?

Example:
```
Products::find()->visible()->all();
```
and usually I create a ProductsQuery with the function below:
```
protected function visible() {
     $this->andWhere('is_visible = 1');
     return $this;
}
```
But I need to overwrite find() in my Model to something like:
```
          return new ProductsQuery(get_called_class());
```
The obvious and current problem is:
```
Calling unknown method: multilingual\MultilingualQuery::visible()
```

is there anyway to apply Custom Scoping, and use the MultilingualBehavior across multiple Models?

**Comment by padlyuck** [comment]
```php
namespace app\models;

use yii\db\ActiveQuery;

class ProductsQuery extends ActiveQuery
{
    use MultilingualTrait;
    public function visible(){
// ...
    }
}
```

**Comment by padlyuck** [comment]
@andreCatita see in the end of  file https://github.com/OmgDef/yii2-multilingual-behavior/blob/master/README.md

**Comment by andreCatita** [comment]
Thanks. Didn't pay close attention.
