### ISSUE TITLE
get languages from db

### ISSUE THREAD

**Issue by sajtosnorbert** [OmgDef/yii2-multilingual-behavior#30]
Hi!

Previously I used the params for the languages, but...

Is there an easy way to get the languages for the behavior from db (ex. language table)?

'languages'       => [
'ru'    => 'Russian',
'en-US' => 'English',
],

This part should be get dynamically from the language table.

Thanks for your answer!

Norbert

**Comment by CyanoFresh** [comment]
Also you have to add support dynamic languages for the form in the view. For subject:
```
'languages' => Lang::getLangsArray(),
```
Lang Model:
```
...
public function getLangsArray()
{
    return self::find()->all();
}
...
```
I've not tested it, it's only example.
