### ISSUE TITLE
Назначение цикла перебора правил валидации

### ISSUE THREAD

**Issue by padlyuck** [OmgDef/yii2-multilingual-behavior#35]
Юрий, подскажите пожалуйста, зачем нужен этот кусок кода https://github.com/OmgDef/yii2-multilingual-behavior/blob/master/src/MultilingualBehavior.php#L173-L200 переменная $validators дальше нигде не используется.

**Comment by OmgDef** [comment]
@padlyuck Для валидации динамических атрибутов модели

**Comment by padlyuck** [comment]
Но массив $validators дальше нигде не используется. Возможно вопрос кажется глупым, но я столкнулся со странным поведением вашей библиотеки. Дело в том, что в консольном приложении если модели задать правила 'default', то они не срабатывают для дефолтного языка.
Так выглядит правило(все поля переводимые)
```php
[['description',  'name', 'project',], 'default', 'value' => '123', 'skipOnEmpty' => false,],
```
Добавляю в базу новый элемент(языки en, ru английский дефолтный)
```php
$model = new \common\models\Liner([
    'code'=>uniqid('liner_'),//непереводимое поле
    'name'=>'test',
    'name_ru'=>'test_ru',
]);
$model->save();
```
В веб приложении таблица выглядит следующим образом
```
language |   name    | description | project
---------+-----------+-------------+--------
   en    |   'test'  |    '123'    |  '123'
---------+-----------+-------------+--------
   ru    | 'test_ru' |    '123'    |  '123'
```
В консольном приложении имею другую картину
```
language |   name    | description | project
---------+-----------+-------------+--------
   en    |   'test'  |     ''      |   '' 
---------+-----------+-------------+--------
   ru    | 'test_ru' |    '123'    |  '123'
```
При этом правила не работают только для языка по-умолчанию

**Comment by OmgDef** [comment]
> Но массив $validators дальше нигде не используется

Переменная ```$validators``` содержит ссылку на массив валидаторов модели.
Валидатором ```default``` не пользовался. Нужно проверить.

**Comment by padlyuck** [comment]
да, мой промах. не обратил внимания, что там не обычный массив.

**Comment by padlyuck** [comment]
Не смог повторить баг на чистом окружении. Видимо проблема кроется где-то в моем проекте.
