### ISSUE TITLE
Search implementation

### ISSUE THREAD

**Issue by Mandzuk** [OmgDef/yii2-multilingual-behavior#70]
Hello. I have read your documentation. But there is a question. Is it possible to implement a search in the main model by the field in the table Lang. For example, I have Post and PostLand models. Fileld title is in PostLand. How I can do search Post::find()->where(['like', 'title', $slug])->all() ?

**Comment by OmgDef** [comment]
Hello. Just use ```joinWith('translations')``` and filter content as usual

**Comment by Mandzuk** [comment]
Здравствуйте. Прошу прощение за долгий ответ. Спасибо, это помогло.
