### ISSUE TITLE
Avoid duplicate content in model table and translation table

### ISSUE THREAD

**Issue by ThomiLee** [OmgDef/yii2-multilingual-behavior#76]
I have a model 'Page' with an attribute 'title'. As long as there is a column 'title' in page table validation works perfectly. But I would like to remove this redundant content since for the application language it is the same as in column 'title' in the translation table. Behavior still works without title column in page table except for the error summary which will show validation errors for title AND for title_en (if application language is English). Any ideas how to solve this?

**Comment by OmgDef** [comment]
@ThomiLee it should work fine. Check your validation rules and other behaviors. If you look through the tests, you will see that I don't use extra columns in a primary table there. https://github.com/OmgDef/yii2-multilingual-behavior/blob/master/tests/MultilingualBehaviorTest.php
https://github.com/OmgDef/yii2-multilingual-behavior/blob/master/tests/migrations/sqlite.sql

**Comment by ThomiLee** [comment]
Thanks for your answer. Of course you are right. I had an error in my configuration and your hint to the test pointed me into the right direction. Great behavior!
