### ISSUE TITLE
Multilingual Model named Attributes

### ISSUE THREAD

**Issue by Trakina** [OmgDef/yii2-multilingual-behavior#8]
Tried to create a model named Attributes and the multilingual "find" command doesn't work. I believe it's related to the fact that the framework uses an "attributes" array to store the model data.
Can this be fixed so that we can use a multilingual model with that name?

**Comment by OmgDef** [comment]
@Trakina I do not think that the model name plays a role. Paste your models and DB schema here.

**Comment by Trakina** [comment]
Here is my schema, this obviously only happens when using multilingual behaviour, if i turn it off, the model works fine.

Here's the Attributes Model: http://pastebin.com/zWFPu2Dy

Also works fine if I rename the model to Attributezzzz or anything else.

![tablez](https://cloud.githubusercontent.com/assets/1686773/6062273/45a23b8a-ad46-11e4-8a6c-94f4fba6bca0.jpg)

**Comment by OmgDef** [comment]
@Trakina fixed in d95cc46d4cc9f7056152f7e182a579cea8067fc3
