### ISSUE TITLE
Creating works good but updating not works. I used la-haute-societe/yii2-save-relations-behavior 

### ISSUE THREAD

**Issue by iAbbos** [OmgDef/yii2-multilingual-behavior#91]
![image](https://user-images.githubusercontent.com/50768679/188799385-9a0d023c-c890-4a23-9356-4f001e464b2a.png)
if I remove SaveRelationsBehavior, updating translations works.

**Comment by OmgDef** [comment]
@iAbbos Just made an example repo. Move ```SaveRelationBehavior``` to the end of your behaviors list and it's gonna work just fine.  https://github.com/OmgDef/yii2-multilingual-example/blob/main/models/Post.php#L91

**Comment by iAbbos** [comment]
Thank you very much. Yes, when I put `MultilingualBehavior` before `SaveRelationsBehavior` everything worked fine.
